// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nggouhjmaewijuqpxwdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nZ291aGptYWV3aWp1cXB4d2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzI5NzYsImV4cCI6MjA2MTUwODk3Nn0.MF9MDknLJmPyZ6WnwurlVeBU9duyM-qI_QpqXCKhKGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);